version: "2"
services:
  screenly-server:
    environment:
      - LISTEN=0.0.0.0
      - IS_DEMO_NODE=1
      - SWAGGER_HOST=ose.demo.screenlyapp.com
    image: screenly/ose-dev-server:latest
    ports:
      - 80:8080
    restart: always
    mem_limit: 300M
    volumes:
      - ./:/home/pi/screenly:ro
      - screenly-assets-volume:/home/pi/screenly_assets
      - screenly-volume:/home/pi/.screenly

volumes:
  screenly-assets-volume:
  screenly-volume:
